version: '3'
services:
  app:
    build: .
    container_name: "app_golang"
    tty: true
    ports:
      - 18888:18888
    volumes:
      - ./src:/go/src/app
    working_dir: /go/src/app/server
    command:
      bash -c 'go build server.go &&
      ./server'